# -*- coding: utf-8 -*-
"""audio sample-1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bqSe5HIdCJ0uZIICFlzJaUikSwbil3jU
"""

!pip install openai-whisper jiwer
import whisper
from google.colab import files
import openai
import whisper
from jiwer import wer

# Step 1: Upload the Audio File
uploaded = files.upload()
audio_file = list(uploaded.keys())[0]

# Step 3: Load Whisper Model and Transcribe
model = whisper.load_model("base")
result = model.transcribe(audio_file)
transcript = result['text']

print("Raw Whisper Transcription:")
print(transcript)

# Step 4: Define the Ground Truth Text
ground_truth_text = "In a world of increasing complexity but decreasing free time, the role of the trusted ‘explainer’ has never been more important. Charles Duhigg is a literal prizewinner in the field and won the Pulitzer Prize for Explanatory Reporting for his team’s series of articles in the New York Times explaining the (not always wonderful) impact of Apple and big tech on the global economy. He’s also the author of the massive bestseller, The Power of Habit. Charles joined us in Manchester to discuss his latest research and book on Supercommunicators which strikes us as the perfect ‘meta’ topic for a TEDx event. We can all appreciate the incredible power of communication. But while we’re all trying to communicate, some of us clearly do it better than others. Why?According to Charles’ latest work, supercommunicators understand that whenever we speak, we’re actually participating in one of three conversations: practical (What’s this really about?), emotional (How do we feel?), and social (Who are we?). If you don’t know what kind of conversation you’re having, you’re unlikely to connect. “Supercommunicators” know the importance of recognizing—and then matching—each kind of conversation and how to hear the complex emotions, subtle negotiations, and deeply held beliefs that color so much of what we say and how we listen. He says that our experiences, our values, our emotional lives—and how we see ourselves and others—shape every discussion, from who will pick up the kids to how we want to be treated at work. Learn why some people are able to make themselves heard, and to hear others, so clearly. Charles Duhigg is a Pulitzer Prize-winning investigative reporter and the author of the international bestsellers The Power of Habit and Smarter Faster Better."
wer_raw = wer(ground_truth_text, transcript)
print(f"WER (Raw Whisper Transcript): {wer_raw}")
''' Whisper transcription was generated for one audio and its word error rate was observed to be 0.28.'''
